### ISSUE TITLE
with-fake-http doesn't support callbacks

### ISSUE THREAD

**Issue by olivergeorge** [d11wtq/http-kit-fake#1]
Currently my callbacks fail unless I add some additional boilerplate to my test fixture.  By adding the ((or callback identity) ...) within my future call the problem is resolved.

Seems like the README needs updating (as below).

Alternatively the with-fake-http could be extended to automatically provide the necessary callback wrapper.

``` clojure
(with-fake-http [#(< (count (% :url)) 20) (fn [orig-fn opts callback]
                                            (future ((or callback identity)
                                                     {:status 418})))]
  (:status @(http/get "http://a.co/"))) ; 418
  (:status @(http/get "http://a.co/" #(println %))) ; nil
```

**Comment by d11wtq** [comment]
Ah yes, this boilerplate is currently needed for the lower level usage. Effectively it's just a hook directly added before the original implementation. I considered making it possible to just return a map, or an integer, or a string, then wrap this return value implicitly. If a future was returned, however, it would be assumed that it provides a full implementation. The reason I omitted this functionality was because I personally couldn't see a use case for it, but then again my problem was probably much simpler (stubbing out a basic external API).

What do you think?

``` clojure
(with-fake-http [#(< (count (% :url)) 20) (fn [orig-fn opts callback] 418)] ; library will provide boilerplate
  (:status @(http/get "http://a.co/"))) ; 418
  (:status @(http/get "http://a.co/" #(println %))) ; nil
```

**Comment by olivergeorge** [comment]
I think implicitly handling things like callbacks would be sensible.

For one, your goal would become being true to the expected functionality of the httpkit request calls (and be explicit about what's not implemented).  Where custom handlers pass back futures that seems tricky to achieve but I'm not so familiar with the code.

On a related note, I am using a function handler because I wanted to handle the {:as :stream} option from httpkit which is not implemented in with-fake-http.

With that in mind perhaps it is worth transparently handling callbacks and making a logical point in the code to add more of the httpkit functionality.

**Comment by d11wtq** [comment]
Sounds good, thanks. I was just about to sit down to write some Clojure, so I guess I'll do this first :octocat:

**Comment by olivergeorge** [comment]
Awesome.

**Comment by d11wtq** [comment]
Ok, I've done this... just trying to recall what my GPG passphrase would be to deploy to Clojars. _scratches head_

**Comment by d11wtq** [comment]
Ah, that was confusing. It was actually my Clojars password I was getting wrong, but `lein deploy` just kept asking for my GPG passphrase. Should be pushed to Clojars as 0.2.1 anyway!
